version: "3"
services:
  install:
    user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
  installTest:
    user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app/test && npm run cp:libs && rm -rf node_modules && rm -f package-lock.json && npm i"
  build: 
    user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"
  buildLib:
    user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run buildLib"   